# Generated by Django 4.1.7 on 2023-04-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
